DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

blog/urls.py
# coding: utf-8
from django.conf.urls import url   	# 导入django的url
from . import views					# 导入当前文件夹下的视图函数

app_name = 'blog'					#

urlpatterns = [						# 关联网址url与视图函数
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
	url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
	url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
	#url(r'^search/$', views.search, name='search'),
	
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blog.feeds import AllPostsRssFeed

# use Django server /media/ files
from django.conf import settings




urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'', include('blog.urls')),     	# 将应用下的视图函数路径包含在工程中，让其识别
	url(r'', include('comments.urls')),     # 将应用下的视图函数路径包含在工程中，让其识别
	
	# 记得在顶部引入 AllPostsRssFeed
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
	
	# 搜索引擎
	url(r'^search/', include('haystack.urls')),
	
	# 编辑框
	url(r'^ueditor/', include('DjangoUeditor.urls' )),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
# coding: utf-8

from django.conf.urls import url

from . import views

app_name = 'comments'

urlpatterns = [
	url(r'comment/post/(?P<post_pk>[0-9])+/$', views.post_comment, name='post_comment'),
]
	

blog/models.py
# coding: utf-8

from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

# 添加编辑框
from DjangoUeditor.models import UEditorField

class Category(models.Model):                       # 文章类别，作为一个数据库表
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name

class Tag(models.Model):                            # 文章标签，作为一个数据库表
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name

class Post(models.Model):							# 文章（类），作为一个数据库表
	title = models.CharField(max_length=70)			# 文章标题
	
	def __str__(self):
		return self.title
	
	# 修改添加编辑框	
	#body = models.TextField()						# 文章内容
	body = UEditorField('内容', height=300, width=1000,
	default=u'', blank=True, imagePath="uploads/images/",
	toolbars='besttome', filePath='uploads/files/')
	
	created_time = models.DateTimeField()			# 文章发布时间
	modified_time = models.DateTimeField()	 		# 文章最后修改时间
	excerpt = models.CharField(max_length=200, blank=True) 	# 文章摘要，允许为空
	category = models.ForeignKey(Category, on_delete=models.CASCADE)			# 文章的类别，关联到Category类，一对多的关系
	tags = models.ManyToManyField(Tag, blank=True)	# 文章标签，关联到Tag类，并且是多对多的关系
	author = models.ForeignKey(User, on_delete=models.CASCADE)				# 文章作者，一对多的关系，关联类User
	views = models.PositiveIntegerField(default=0)	# 显示阅读量
	
	# 获取定义好的url reverse 第一个参数‘blog：detail’，匹配blog
	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'pk': self.pk})
	
	class Mate:
		ordering = ['-created_time', 'title'] 
	
	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])
		
	def save(self, *args, **kwargs):
		# 如果没有手写摘要
		if not self.excerpt:
			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
				])
			self.excerpt = strip_tags(md.convert(self.body))[:54]
			
		super(Post, self).save(*args, **kwargs)

comments/models.py
# coding: utf-8

from django.db import models

# Create your models here.

#from django.utils.six import python_2_unicode_compatible

# python_2_unicode_compatible 装饰器用于兼容 Python2

class Comment(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=255)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)
	post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)
	
	def __str__(self):
		return self.text[:20]
		

blog/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404

# Create your views here.
import markdown
from django.http import HttpResponse
from .models import Post, Category, Tag
from comments.forms import CommentForm

from django.views.generic import ListView, DetailView    # 使用类视图函数

from django.db.models import Q

def index(request):
	#return HttpResponse("你好，世界！")
	#return render(request, 'blog/index.html', context={
	#				'title': '我的博客首页',
	#				'welcome':'欢迎访问我的博客首页',
	#				})
	#				
	post_list = Post.objects.all()#.order_by('-created_time')
	#comment_list = post_list.comment_set.all()
	#context = {	'post_list': post_list,
	#			'comment_list':comment_list,
	#			}
	return render(request, 'blog/index.html', context={'post_list': post_list})
	
def about(request):
	return render(request, 'blog/about.html', )
	
def contact(request):
	return render(request, 'blog/contact.html', )
	

def detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.increase_views()                    # 获取阅读量
	post.body = markdown.markdown(post.body, # 语法高亮
								  extensions=[
									'markdown.extensions.extra',
									'markdown.extensions.codehilite',
									'markdown.extensions.toc',
									])
	form = CommentForm()
	comment_list = post.comment_set.all()
	context = {	'post':post,
				'form':form,
				'comment_list':comment_list
		}
	return render(request, 'blog/detail.html', context=context)
	#return render(request, 'blog/detail.html', context={'post':post})
	
def archives(request, year, month):
	post_list = Post.objects.filter(created_time__year=year,
									created_time__month=month,
									)
	return  render(request, 'blog/index.html', context={'post_list':post_list})

def category(request, pk):
	cate = get_object_or_404(Category, pk=pk)
	post_list = Post.objects.filter(category=cate)
	return render(request, 'blog/index.html', context={'post_list': post_list})
	
# 搜索获取（关键字为标题和文章详情）	
def search(request):
	str = request.GET.get('str')
	error_msg = ''
	
	if not str:
		error_msg = "请输入关键词"
		return render(request, 'blog/index.html', {'error_msg':error_msg})
		
	post_list = Post.objects.filter(Q(title__icontains=str) | Q(body__icontains=str))
	return render(request, 'blog/index.html', {'error_msg':error_msg, 'post_list':post_list})
							

class IndexView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'
	paginate_by = 3
	
	def get_context_data(self, **kwargs):

        # 首先获得父类生成的传递给模板的字典。
		context = super().get_context_data(**kwargs)
		
		# 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')
		
		# 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
		pagination_data = self.pagination_data(paginator, page, is_paginated)
		
		# 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
		context.update(pagination_data)
		
		# 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
		return context
		
	def pagination_data(self, paginator, page, is_paginated):
		# 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
		if not is_paginated:
			return {}
			
		# 当前页左边连续的页码号，初始值为空
		left = []
		# 当前页右边连续的页码号，初始值为空
		right = []
		 # 标示第 1 页页码后是否需要显示省略号
		left_has_more = False
		# 标示最后一页页码前是否需要显示省略号
		right_has_more = False
		first = False
		last = False
		page_number = page.number
		total_pages = paginator.num_pages
		page_range = paginator.page_range
		
		if page_number == 1:
			right = page_range[page_number:page_number + 2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True
		elif page_number == total_pages:
			left = page_range[(page_number-3) if (page_number-3) > 0 else 0:page_number-1]
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True
		else:
			left = page_range[(page_number-3) if (page_number-3) > 0 else 0:page_number-1]
			right = page_range[page_number:page_number + 2] 
			
			if right[-1] < total_pages -1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True
				
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True
		data = {
			'left':left, 
			'right':right,
			'left_has_more':left_has_more, 
			'right_has_more':right_has_more, 
			'first':first, 
			'last':last, 
			}
		return data
				
class CategoryView(IndexView):
	def get_queryset(self):
		cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
		return super(CategoryView, self).get_queryset().filter(category=cate)

class ArchivesView(IndexView):
	def get_queryset(self):
		year = self.kwargs.get('year')
		month = self.kwargs.get('month')
		return super(ArchivesView, self).get_queryset().filter(created_time__year=year,created_time__month=month)

class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/detail.html'
	context_object_name = 'post'
	
	def get(self, request, *args, **kwargs):
		response = super(PostDetailView, self).get(request, *args, **kwargs)
		self.object.increase_views()
		return response
	
	def get_object(self, queryset=None):
		post = super(PostDetailView, self).get_object(queryset=None)
		post.body = markdown.markdown(post.body,
										extensions=[
										'markdown.extensions.extra',
										'markdown.extensions.codehilite',
										'markdown.extensions.toc',
										])
		return post
		
	def get_context_data(self, **kwargs):
		context = super(PostDetailView, self).get_context_data(**kwargs)
		form = CommentForm()
		comment_list = self.object.comment_set.all()
		context.update({
			'form':form, 
			'comment_list':comment_list
			})
		return context

class TagView(IndexView):
	def get_queryset(self):
		tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
		return super(TagView, self).get_queryset().filter(tags=tag)
		
		

		
	


	

templates/blog/about.html
{% extends 'base_ac.html' %}
{% load staticfiles %}
{% block main %}

<h1 class="page-title">About me</h1>
<article class="post">
	<div class="entry-content clearfix">
		<p></p>
		<p></p>
		<div class="height-40px"></div>
		
		<figure class="img-responsive-center">
			<img class="img-responsive" src="{% static 'blog/img/batman_logo.gif' %}" alt="Developer Image">
		</figure>
		
		<h2 class="title text-center">Social</h2>
		<ul class="social">
			<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
			<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
			<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
			<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
		</ul>
	</div>
</article>
	
{% endblock main %}

templates/blog/contact.html
{% extends 'base_ac.html' %}
{% load staticfiles %}
{% block main %}

<h1 class="col-md-offset-2">Contact</h1>
<article class="post">
	<div class="entry-content clearfix">
		<form action="#" method="post" class="contact-form">
			<div class="row">
				<div class="col-md-5 col-md-offset+2">
					<input type="text" name="name" placeholder="Name" required>
					<input type="email" name="email" placeholder="Email" required>
					<input type="text" name="subject" placeholder="Subject" required>
					<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
					<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
				</div>
			</div>	<!-- row -->
		</form>
		
	</div>
</article>
	
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
	<article class="post post-{{ post.pk }}">
		<header class="entry-header">
			<h1 class="entry-title">{{ post.title }}</h1>
				<div class="entry-meta">
					<span class="post-category"><a href="#">{{ post.category.name }}</a></span>
					
					{% for tag in post.tags.all %}
					<span class="post-tag"><a href="#">{{ tag.name }}</a></span>
					{% endfor %}
					
					<span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
					<span class="post-author"><a href="#">{{ post.author }}</a></span>
					<span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
					<span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
				</div>
         </header>
		 <div class="entry-content clearfix">
			{{ post.body|safe }}
		</div>
	</article>
	<section class="comment-area">
		<hr>
		<h3>发表评论</h3>
		<form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-4">
					<label for="form.name.id_for_label">名字：</label>
					{{ form.name }}
					{{ form.name.errors }}
				</div>
				<div class="col-md-4">
					<label for="form.email.id_for_label">邮箱：</label>
					{{ form.email }}
					{{ form.email.errors }}
				</div>
				<div class="col-md-12">
					<label for="form.text.id_label">评论：</label>
					{{ form.text }}
					{{ form.text.errors }}
					<button type="submit" class="comment-btn">发表</button>
				</div>
			</div>    <!-- row -->
		</form>
		<div class="comment-list-panel">
			<h3>评论列表，共 <span>{{ comment_list | length }}</span> 条评论</h3>
			<ul class="comment-list list-unstyled">
				{% for comment in comment_list %}
				<li class="comment-item">
					<span class="nickname">{{ comment.name }}</span>
					<time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
					<div class="text">
						{{ comment.text }}
					</div>
				</li>
				{% empty %}
				暂无评论！
				{% endfor %}
			</ul>
		</div>
	</section>
{% endblock main %}
{% block toc %}
	<div class="widget widget-content">
		<h3 class="widget-title">文章目录</h3>
		<ul>
			<li>
				<a href="#">教程特点</a>
			</li>
			<li>
				<a href="#">谁适合这个教程</a>
			</li>
			<li>
				<a href="#">在线预览</a>
			</li>
			<li>
				<a href="#">资源列表</a>
			</li>
			<li>
				<a href="#">获取帮助</a>
			</li>
		</ul>
	</div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
	
	{% if error_msg %}
    <p>{{ error_msg }}</p>
	{% endif %}


	{% for post in post_list %}
		<article class="post post-{{ post.pk }}">
			<header class="entry-header">
				<h1 class="entry-title">
					<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
				</h1>
				<div class="entry-meta">
					<span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
					
					{% for tag in post.tags.all %}
					<span class="post-tag"><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></span>
					{% endfor %}
					
					<span class="post-date"><a href="{% url 'blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
					<span class="post-author"><a href="#">{{ post.author }}</a></span>
					<span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
					<span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
				</div>
			</header>
			<div class="entry-content clearfix">
				<p>{{ post.excerpt }}...</p>
				<div class="read-more cl-effect-14">
					<a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
				</div>
			</div>
		</article>
	{% empty %}
		<div class="no-post">暂时还没有发布文章,敬请期待</div>
	{% endfor %}

	
	
	{% if is_paginated %}
	<ul class="pagination">
		{% if first %}
			<li><a href="?page=1">1</a></li>
		{% endif %}
		
		{% if left %}
			{% if left_has_more %}
				<span>...</span>
			{% endif %}
			{% for i in left %}
				<li><a href="?page={{ i }}">{{ i }}</a></li>
			{% endfor %}
		{% endif %}
		<li><a class="active" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
		{% if right %}
			{% if right_has_more %}
				<span>...</span>
			{% endif %}
			{% for i in right %}
				<li><a href="?page={{ i }}">{{ i }}</a></li>
			{% endfor %}
		{% endif %}
		{% if last %}
			<li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
		{% endif %}	
	</ul>
	{% endif %}
	
	
	
{% endblock main %}
            